info:
  app:
    name: My App
    description: Cool :)
    version: 1.0.0

spring:
  datasource:
#  security:
#    user:
#      name: admin
#      password: topsecret
    url: jdbc:h2:tcp://localhost/~/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: bean, mapping
      base-path: /actuator

